theme = "panda"

[editor]
bufferline = "always"
color-modes = true  # Use colours for NOR, INS, SEL in the status bar
file-picker.hidden = false  # Show hidden files
indent-guides.render = true
rulers = [80, 100, 120]
soft-wrap.enable = true  # Use space.B below to toggle
trim-final-newlines = true
trim-trailing-whitespace = true
true-color = true  # TODO fix true colour support over SSH
whitespace.render = { nbsp = "all", nnbsp = "all", tab = "all", space="all" }

[keys.normal]
# Print the current line's git blame information to the statusline.
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
# Toggle soft wrap with alt-Z
space.W = ":toggle soft-wrap.enable"
