theme = "llama"

[editor]
bufferline = "always"
color-modes = true  # Use colours for NOR, INS, SEL in the status bar
file-picker.hidden = false  # Show hidden files
indent-guides.render = true
popup-border = "all"
rulers = [80, 100, 120]
scroll-lines = 1
soft-wrap.enable = true  # Use space.W below to toggle
trim-final-newlines = true
trim-trailing-whitespace = true
true-color = true
whitespace.render = { nbsp = "all", nnbsp = "all", space = "all", tab = "all" }

[keys.normal]
G = "goto_file_end"
S-tab = ":buffer-previous"
X = "select_line_above"
g.G = "goto_file_end"
space.W = ":toggle soft-wrap.enable"
tab = ":buffer-next"

[keys.select]
G = "extend_to_file_end"
g.G = "extend_to_file_end"

[keys.normal.C-g]
a = ":echo Git added: %sh{git add %{buffer_name} && echo '%{buffer_name}'}"
b = ":echo Git blame: %sh{git blame -L %{cursor_line},+1 %{buffer_name} | awk '{print $1}' | xargs git log -n 1 --pretty='%%h - %%s (%%cr) <%%an>'}"
d = ":sh git blame -L %{cursor_line},+1 %{buffer_name} | awk '{print $1}' | xargs git log -n 1"
D = ":sh git blame -L %{cursor_line},+1 %{buffer_name} | awk '{print $1}' | xargs git log -n 1 --patch"
g = "changed_file_picker"
"?" = ":echo Git branch name: %sh{git rev-parse --abbrev-ref HEAD}"
