# Theme: Llama
# Author: Liam Newmarch

# Editor UI
"ui.background.separator" = "bright-black"
"ui.bufferline" = { fg = "white", modifiers = ["dim"] }
"ui.bufferline.active" = { bg = "white", fg = "black", modifiers = ["bold"] }
"ui.bufferline.background" = { bg = "black-1" }
"ui.cursor" = { bg = "white", modifiers = ["dim"] }
"ui.cursor.insert" = { fg = "magenta", modifiers = ["reversed"] }
"ui.cursor.normal" = { fg = "white", modifiers = ["dim", "reversed"] }
"ui.cursor.match" = { modifiers = ["dim", "reversed"] }
"ui.cursor.primary.insert" = { bg = "magenta", fg = "black-0" }
"ui.cursor.primary.normal" = { bg = "white", fg = "black-0" }
"ui.cursor.primary.select" = { bg = "white", fg = "black-0" }
"ui.cursor.select" = { fg = "white", modifiers = ["dim", "reversed"] }
"ui.gutter" = "black"
"ui.gutter.selected" = "bright-white"
"ui.highlight" = { bg = "black" }
"ui.linenr" = { fg = "bright-black", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "bright-white", modifiers = ["bold"] }
"ui.menu" = { fg = "white", bg = "black-1" }
"ui.menu.scroll" = "magenta"
"ui.menu.selected" = { fg = "magenta",  modifiers = ["reversed"] }
"ui.popup" = { bg = "black-0" }
"ui.selection" = { bg = "blue", fg = "black-0", modifiers = ["dim"] }
"ui.selection.primary" = { bg = "blue", fg = "black-0", modifiers = [] }
"ui.statusline" = { bg = "black-1", fg = "white" }
"ui.statusline.inactive" = { modifiers = ["dim"] }
"ui.statusline.insert" = { bg = "magenta", fg = "black-0" }
"ui.statusline.normal" = { bg = "white", fg = "black-0" }
"ui.statusline.select" = { bg = "blue", fg = "black-0" }
"ui.text" = "white"
"ui.text.focus" = "magenta"
"ui.virtual.indent-guide" = "black"
"ui.virtual.ruler" = { bg = "#0b0b0b" }
"ui.virtual.whitespace" = "black"
"ui.virtual.wrap" = "black"
"ui.window" = "black"

# Syntax highlighting
# TODO add hex codes to colour palette and replace
"attribute" = "#87BCF6"
"comment" = "bright-black"
"constant" = "#F1A865"
"constant.character.escape" = "#87BCF6"
"constant.numeric" = "#F1A865"
"constructor" = "#87BCF6"
"function" = "#87BCF6"
"function.builtin" = { fg = "#87BCF6", modifiers = ["bold"] }
"function.macro" = "light-red"
"keyword" = "#F1A865"
"keyword.control.conditional" = "#F56BA6"
"keyword.control.exception" = "#F56BA6"
"keyword.directive" = { fg = "#F1A865", modifiers = ["bold"] }
"keyword.operator" = { fg = "#87BCF6", modifiers = ["bold"] }
"label" = "#31F3D1"
"namespace" = "#87BCF6"
"punctuation.bracket" = "#1F7CCD"
"special" = "#F56BA6"
"string"  = "#31F3D1"
"tag" = "bright-magenta"
"type" = "#87BCF6"
"type.builtin" = "#F56BA6"
"type.enum.variant" = "white"
"variable" = "white"
"variable.other.member" = "white"
"variable.parameter" = { fg = "#87BCF6", modifiers = ["italic"] }
"varibale.builtin" = "#87BCF6"
"varibale.other.member" = "#87BCF6"
"varibale.other.member.private" = "#87BCF6"
"varibale.parameter" = "#87BCF6"

"markup.bold" = { fg = "#31F3D1", modifiers = ["bold"] }
"markup.heading" = "#87BCF6"
"markup.italic" = { fg = "#87BCF6", modifiers = ["italic"] }
"markup.link.text" = "light-magenta"
"markup.link.url" = { fg = "magenta", modifiers = ["dim"] }
"markup.list" = "#F1A865"
"markup.quote" = "#31F3D1"
"markup.raw" = "light-green"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diff.delta" = "blue"
"diff.minus" = "red"
"diff.plus" = "green"

"diagnostic.error" = { underline = { color = "light-red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "gray", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }

"debug" = "white"
"error" = "red"
"hint" = { fg = "light-gray", modifiers = ["dim"] }
"info" = "blue"
"warning" = "yellow"

[palette]
# Panda-style colours, duplicated from alacritty config
black = "#29292a"
red = "#ea436e"
green = "#75f8dc"
yellow = "#f4ba78"
blue = "#7caff8"
magenta = "#ed7db2"
cyan = "#75f8dc"
white = "#f2f2f2"

bright-black = "#707681"
# bright-red = "#ea436e"
# bright-green = "#75f8dc"
bright-yellow = "#f6cb97"
bright-blue = "#7abaf9"
bright-magenta = "#f2add6"
# bright-cyan = "#75f8dc"
bright-white = "#ffffff"

black-0 = "#000000"
black-1 = "#111111"
